# Generated by Django 5.2.7 on 2025-11-09 23:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContenuPedagogique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('fichier', models.FileField(upload_to='contenus/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('pdf_file', models.FileField(upload_to='pdfs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(choices=[('APD', 'APD'), ('DBE', 'DBE'), ('DFE', 'DFE'), ('RSIOT', 'RSIOT')], max_length=10, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exercice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('fichier', models.FileField(upload_to='exercices/')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.filiere')),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('profile_picture', models.ImageField(blank=True, default='profiles/default.png', null=True, upload_to='profiles/')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='pdfs/')),
                ('bulletin', models.FileField(blank=True, null=True, upload_to='bulletins/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('filiere', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myApp.filiere')),
            ],
        ),
        migrations.CreateModel(
            name='EmploiDuTemps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('fichier', models.FileField(upload_to='emplois/')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.filiere')),
            ],
        ),
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('fichier', models.FileField(upload_to='cours/')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.filiere')),
            ],
        ),
        migrations.CreateModel(
            name='Responsable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('departement', models.CharField(blank=True, max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
