# Generated by Django 5.2.7 on 2025-11-11 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiant',
            name='pdf_file',
        ),
        migrations.AddField(
            model_name='etudiant',
            name='diplome',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='pdf_file',
            field=models.FileField(upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='filiere',
            name='nom',
            field=models.CharField(choices=[('APD', 'APD'), ('DBE', 'DBE'), ('DFE', 'DFE'), ('RSIOT', 'RSIOT')], max_length=50, unique=True),
        ),
    ]
