# Generated by Django 5.2.7 on 2025-11-12 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_remove_etudiant_pdf_file_etudiant_diplome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenupedagogique',
            name='responsable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myApp.responsable'),
        ),
        migrations.AddField(
            model_name='cours',
            name='responsable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myApp.responsable'),
        ),
        migrations.AddField(
            model_name='emploidutemps',
            name='responsable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myApp.responsable'),
        ),
        migrations.AddField(
            model_name='exercice',
            name='responsable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myApp.responsable'),
        ),
    ]
