# Generated by Django 5.2.7 on 2025-11-14 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_contenupedagogique_responsable_cours_responsable_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiant',
            name='bulletin',
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='diplome',
        ),
    ]
